[package]
name = "single-variable-algebra-compiler"
version = "0.1.0"
authors = ["Armin Schäfer"]
description = "A compiler for the minimalistic programming language single-variable-algebra."
repository = "https://github.com/772/single-variable-algebra-compiler"
readme = "README.md"
license-file = "LICENSE"
edition = "2024"
categories = ["compilers"]
keywords = ["compiler"]

[dependencies]
dec = "0.4"
serde = { version = "1.0", features = ["derive"] }
